language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- export APP_SETTINGS="project.config.TestingConfig"
- export APP_MAIL_USERNAME="skedd.mail@gmail.com"
- export APP_MAIL_PASSWORD="cumulonimbus"
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: AIMQRHvgfRKMqQUa7OCAhmJLaq6sJrYLJ9X6JU+425+dQpnMYH8p/ZpvgM7FjWcNUllD+u0cx9cGZTkRzJr0jO2/g8Sybdc+gok3RmuljNF/RG+1FdIJD+wT38KNhugGXnZ6iTgToe+ownhRLcOgyWjewSKw9bp94ndzTPsfM88M0fZllBqTbosznvydobaRSSY16jrrw0SAFWehUMFg0MFH0n1hXWTUSzgLQ/5MP1VwxsXlnPubO1u28TNmjVyn/fUD8JToMKXfUBQe9EBmCbL35BanVcrFrkcnXeLYZGLrPKh7rL3+YfP9uAdeh6BH2p9pHDMsS0CltZMlGUIx68Dx7VJ9+a0D7xravBpPepYUEpEWdrOe3+hFXPWfh5c/bnYkyBUOSidGPT1wgDkpURV2qY5Evh40kPJb2M1FPF6A2aqUPA6MqJgDArmy4OxCsKFgs0CV1H9rHJsE0+YxTBnOWVXKsir6rnZsFbPD3xbtwC4mbJPg+WQznZGtLBCNUZJ4uuXl9Fcygd2LcC1f5vLAzMVBIbWq8Bqn7a7qrWaFNKIwOOPEO8M+L5xt+1y2TX9Ao2zf4kz6hLyLpqCxExobzIP2fyp+/TRXfBOquXi3OpA/YqX95kHOG4PFOjIxIvEUPkpLagTCqGDv8RagmjTfCMu9UBLip+41BMddlf8=
  app: SKEDD
  on:
    repo: CameronOC/SKEDD
