language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- export APP_SETTINGS="project.config.TestingConfig"
- export APP_MAIL_USERNAME="skedd.mail@gmail.com"
- export APP_MAIL_PASSWORD="cumulonimbus"
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: "KSS8QvJgGxhm7Sa6AlaImb0iozquycOI3u9/AI9bLNNLE9ZOzSvHZwvNQAvrQR/szbl0jnrIcDyHdco7NquOPEADZeXhq/WLN+lE9V5RAK6uIEN3Vf4jM+MaAZhS6sQpmVxNi7GnQnl82KPT9/+o3+1/bag9kuInILfKp6RWkijYQBf/nAN5csw7rXxxhcX7cGPTZ8DpOXlhqroES56uiVZhRG5kH3Y015mU1ca70fN9ufnWS18RZCCrLinPI2xmejlCNt+YNbyvXRvz1JL+0viLQPAqwulgYfNsGZr5uIAN9ROgETAR7FiroVJlMbpztktzyktLrUh5tToGbS1QiYaNbH2vUOIBwmEKzrKVteA+Voim7VvRg2duEOT36oO95Gt+qPiw/mtPYfM4x7pq7rC3JlZqmHV2is7/3DcxjmtFAMB4KyCwlqxgjf6a+r/Q2OdW893Ypdjr2M9EJ7IChRx+THxP1UkfMJaYuBHxbdu/+CRrA8d5oj+AnaNND1xulaks16Qqiemnv2jGR97eNTWy/OqV7U5f+QNav8mpbjIIrC09DHviuecg4HpeGCw7VNpaKhK2qKU7EYxWPddIo8dsu7Ed4y2XZaIn3WwdGX/StAkhYNh3jMMYooMh2ZMgApDQh0Ck4wjfLPONAU4J9LZBirSAfyZQR+lPSfSGwEk="
