language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- export APP_SETTINGS="project.config.TestingConfig"
- export APP_MAIL_USERNAME="skedd.mail@gmail.com"
- export APP_MAIL_PASSWORD="cumulonimbus"
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: K97oO0r1BzIIKMsbjLqeQOiFdmQ8ZRUEF8pGeWrFMy6nHjBXHRcfqifoMCcvLHuxQ8LepdSs7P6BIRUfs0XZrVHse4X2RVkWrRkv2g/cHbFcCu9Gle2E/tykLNgSeQzE1pAx61kDdO4dPQM8zKtlTj0WpDYTzlizLiCekBvDd4tmBOrG4O7g2SNGQsyThVLHIVLXUkxAWkbu1kmn84FuZazMtmOUlhxvLVYSTwWvT9CGDrvHlwnqHCft1u0Onv5g/plUW7A2lfxNMWhiJv91pFnDNHZ4QWOIEvQSCz9q28regRptuQwWmI4q+vQ7dTAWak5wynG7KKGwTa9uIwga93sB5R3xnnooxMbPJAWdbIiuvsUJOTT/NTiuFsC92u6xFHH9toKqtzBp0OXxTPBqJL1fDl2XW0rcJ8eFfGShN/z5aChTsZAqTXEvkutIN5xnt9KZvDoGExkmLBozeHxg7mJKDC/WisUzJv9Q33ekDzrxs2JHGj9cgHBHsDueu0PeSAwoNE9g/o4Xyk8x/oivrNkISL2oioK3jK65ljf//opJdlFSPD3UVAm78vDZT266x27voOlR6vDaACb1KXLpHPU9b7nYmpLRRsUjXFoqqlIxvR7orQwzgRX6pVVh0K3cM/m2T/lYUuRRlX07qtrG2ddFttW/xrqm5HcCBkJ4syY=
  app: SKEDD
  on:
    repo: CameronOC/SKEDD
