language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- export APP_SETTINGS="project.config.TestingConfig"
- export APP_MAIL_USERNAME="skedd.mail@gmail.com"
- export APP_MAIL_PASSWORD="cumulonimbus"
script:
- nosetests
